
name: "Request issue "
description: this is create request issue
body:
- type: textarea
  attributes:
    label: template_word1
    value: "# 依頼書"
      
- type: textarea
  id: request_content
  attributes:
    label: 依頼内容
    placeholder: "依頼内容を記入"
  validations:
    required: false

- type: input
  id: target_server
  attributes:
    label: 対象環境
    placeholder: "対象環境を記入"
  validations:
    required: false

- type: input
  id: target_site
  attributes:
    label: 対象サイト
    placeholder: "対象サイトを記入"
  validations:
    required: false
    
- type: textarea
  attributes:
    label: template_word2
    value:  |
      ### ファイル格納先
      
      [リンク](https://www.google.com/)
      
      ### 承認
      
      | 担当 | 名前 | 日付 |
      | :---: | :---: |  :---: | 
      |   者 |||
      |   者 |||
      |   者 |||
      
      ---
      
      # 報告書
      
      ### 報告内容
      
      ### 作業実施日      
      
      ### 承認
      
      | 担当 | 名前 | 日付 |
      | :---: | :---: |  :---: | 
      |   者 |||
      |   者 |||
      |   者 |||

